# Author: Justin Chen <ctj12461@163.com>

inherits = "tokyonight_storm"

"ui.background" = { fg = "foreground" }
"ui.cursorline.primary" = { bg = "cursorline" }
"ui.help" = { fg = "foreground" }
"ui.menu" = { fg = "foreground" }
"ui.menu.selected" = { bg = "background_highlight" }
"ui.popup" = { fg = "foreground"}
"ui.statusline" = { fg = "foreground" }
"ui.statusline.inactive" = { fg = "foreground_gutter" }

[palette]
background_highlight = "#6c76a6"
foreground_gutter = "#6c76a6"
comment = "#b6bbd3"
# cursorline = "#41496b